## Question 1 : Replace all odd numbers in arr with -1 without changing arr

In [22]:
import numpy as np

InputArray = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#replacing the odd numbers in the array by -1
OutputArray = np.where(InputArray % 2 == 1, -1,InputArray)

print("The original array : " ,InputArray)
print("The result array : " , OutputArray)

The original array :  [0 1 2 3 4 5 6 7 8 9]
The result array :  [ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Question 2 : Get the common items between two python numpy arrays


In [17]:
import numpy as np

InputArray1 = np.array([1,2,3,2,3,4,3,4,5,6])
InputArray2 = np.array([7,2,10,2,7,4,9,4,9,8])

print("Array 1 : ", InputArray1)
print("Array 2 : ", InputArray2)

# Common values between two numpy arrays
print("The common items in both arrays are: ", np.intersect1d(InputArray1, InputArray2))

Array 1 :  [1 2 3 2 3 4 3 4 5 6]
Array 2 :  [ 7  2 10  2  7  4  9  4  9  8]
The common items in both arrays are:  [2 4]


## Question 3 : From array a remove all items present in array b


In [21]:
import numpy as np

InputArray1 = np.array([1,2,3,4,5])
InputArray2 = np.array([5,6,7,8,9])

#remove array1 all items present in array2
OutputArray = np.setdiff1d(InputArray1, InputArray2)

print("Array 1 : ", InputArray1)
print("Array 2 : ", InputArray2)
print("Difference of Array 1 and Array 2: ", OutputArray)

Array 1 :  [1 2 3 4 5]
Array 2 :  [5 6 7 8 9]
Difference of Array 1 and Array 2:  [1 2 3 4]


## Question4 : Swap rows 1 and 2 in the array

In [28]:
import numpy as np

InputArray = np.arange(9).reshape(3,3)
print("Original Array after swap operation : \n" , InputArray)

#swapping rows 1 and 2
InputArray[[1, 2]] = InputArray[[2, 1]]
print("\nResult Array after swap operation : \n", InputArray)

Original Array after swap operation : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Result Array after swap operation : 
 [[0 1 2]
 [6 7 8]
 [3 4 5]]


## Question 5 : Swap columns 1 and 2 in the array

In [30]:
import numpy as np

InputArray = np.arange(9).reshape(3,3)
print("Original Array after swap operation : \n" , InputArray)

#swapping columns 1 and 2
InputArray[:,[1, 2]] = InputArray[:,[2,1]]
print("\nResult Array after swap operation : \n", InputArray)

Original Array after swap operation : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Result Array after swap operation : 
 [[0 2 1]
 [3 5 4]
 [6 8 7]]


## Question 6 : 

### a. Import the iris dataset keeping the text intact.
### b. Extract the text column “species” from the 1D iris imported in previous question


In [59]:
import numpy as np

dataPath = 'iris.data'
irisData = np.genfromtxt(dataPath, delimiter=',', dtype='object')

#dataset keeping the text intact
print("The IRIS Dataset : \n\n", irisData[:4], "\n")

iris_1d = np.genfromtxt(dataPath, delimiter=',', dtype=None)

#shape of the iris dataset
print("Shape of IRIS dataset : ",iris_1d.shape , "\n")

#extracting species column from 1D iris
species = np.array([row[4] for row in iris_1d])
print("Column - SPECIES from 1D IRIS :",species[:5])

The IRIS Dataset : 

 [[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']] 

Shape of IRIS dataset :  (150,) 

Column - SPECIES from 1D IRIS : [b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


<ipython-input-59-ded2f786a394>:9: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(dataPath, delimiter=',', dtype=None)


## Question 7 : Import the csv data from here, you will see some missing data.
### a. Find out what percent of the sf_permit dataset is missing
### b. Look at the columns Street Number Suffix and Zipcode from the sf_permits datasets. Both of these contain missing values. Which, if either, of these are missing because they don't exist? Which, if either, are missing because they weren't recorded?
### c. Try removing all the rows from the sf_permits dataset that contain missing values. How many are left?
### d. Now try removing all the columns with empty values. Now how much of your data is left?¶
### e. Try replacing all the NaN's in the sf_permit data with the one that comes directly after it and then [replace all the remaining na's with 0]


In [53]:
import numpy as np
import pandas as pd

#importing the csv data into dataset
dataset = pd.read_csv('Building_Permits.csv') 

totalCells = np.product(dataset.shape)

# Count number of missing values per column
missingCount = dataset.isnull().sum()

# Calculate total number of missing values
totalMissing = missingCount.sum()

# Calculate percentage of missing values
print("A. ")
print("The SF Permits dataset contains", round(((totalMissing/totalCells) * 100), 2), "%", "missing values.")

missingCount[['Street Number Suffix', 'Zipcode']]
print("B. ")
print("Percent missing data in Street Number Suffix column =", (round(((missingCount['Street Number Suffix'] / dataset.shape[0]) * 100), 2)))
print("Percent missing data in Zipcode column =", (round(((missingCount['Zipcode'] / dataset.shape[0]) * 100), 2)))

print("C. ")
sfPermitsCleanCols = dataset.dropna()
print("Columns in original dataset: %d" % dataset.shape[1])
print("Columns with missing values dropped: %d" % sfPermitsCleanCols.shape[1])

print("D. ")
sfPermitsCleanCols = dataset.dropna(axis=1)
sfPermitsCleanCols.head()
print("Columns in original dataset: %d" % dataset.shape[1])
print("Columns with na's dropped: %d" % sfPermitsCleanCols.shape[1])

print("E. ")
imputeSfPermits = dataset.fillna(method='ffill', axis=0).fillna("0")
imputeSfPermits.head()

/home/knoldus/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (22,32) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


A. 
The SF Permits dataset contains 26.26 % missing values.
B. 
Percent missing data in Street Number Suffix column = 98.89
Percent missing data in Zipcode column = 0.86
C. 
Columns in original dataset: 43
Columns with na's dropped: 43
D. 
Columns in original dataset: 43
Columns with na's dropped: 12
E. 


Permit Number  Permit Type            Permit Type Definition  \
0  201505065519            4                      sign - erect   
1  201604195146            4                      sign - erect   
2  201605278609            3  additions alterations or repairs   
3  201611072166            8            otc alterations permit   
4  201611283529            6                       demolitions   

  Permit Creation Date Block  Lot  Street Number Street Number Suffix  \
0           05/06/2015  0326  023            140                    0   
1           04/19/2016  0306  007            440                    0   
2           05/27/2016  0595  203           1647                    0   
3           11/07/2016  0156  011           1230                    0   
4           11/28/2016  0342  001            950                    0   

  Street Name Street Suffix  ... Existing Construction Type  \
0       Ellis            St  ...                        3.0   
1       Geary            St  ...                        3.0   
2     Pacific            Av  ...                        1.0   
3     Pacific            Av  ...                        5.0   
4      Market            St  ...                        3.0   

  Existing Construction Type Description Proposed Construction Type  \
0                          constr type 3                          0   
1                          constr type 3                          0   
2                          constr type 1                        1.0   
3                         wood frame (5)                        5.0   
4                          constr type 3                        5.0   

  Proposed Construction Type Description Site Permit Supervisor District  \
0                                      0           0                 3.0   
1                                      0           0                 3.0   
2                          constr type 1           0                 3.0   
3                         wood frame (5)           0                 3.0   
4                         wood frame (5)           0                 6.0   

  Neighborhoods - Analysis Boundaries  Zipcode  \
0                          Tenderloin  94102.0   
1                          Tenderloin  94102.0   
2                        Russian Hill  94109.0   
3                            Nob Hill  94109.0   
4                          Tenderloin  94102.0   

                                    Location      Record ID  
0  (37.785719256680785, -122.40852313194863)  1380611233945  
1   (37.78733980600732, -122.41063199757738)  1420164406718  
2    (37.7946573324287, -122.42232562979227)  1424856504716  
3   (37.79595867909168, -122.41557405519474)  1443574295566  
4   (37.78315261897309, -122.40950883997789)   144548169992  

[5 rows x 43 columns]